### ISSUE TITLE
[gcc torture d8] memory access out of bounds

### ISSUE THREAD

**Issue by binji** [WebAssembly/waterfall#18]
Many of these failures seem to be a result of s2wasm generating 0 for `__stack_pointer`.

**Comment by kripken** [comment]
Would it help to hardcode some special behavior in s2wasm? Perhaps the stack pointer is special enough that it warrants that.

**Comment by jfbastien** [comment]
@dschuff was working on this, maybe we won't need the hack soon. @dschuff what would be best?

**Comment by dschuff** [comment]
Isn't s2wasm the thing that is actually supposed to assign the location for __stack_pointer, acting in its role as linker?

**Comment by jfbastien** [comment]
@dschuff : https://github.com/WebAssembly/binaryen/blob/22ed7f49494e6ecf6c431b40ab6961953c2e3a8b/src/s2wasm.h#L346

**Comment by kripken** [comment]
Yes, conceptually it's at the "link" stage, so I agree it's reasonable to have s2wasm do this. Sounds like there's agreement so I pushed https://github.com/WebAssembly/binaryen/commit/627b4f16433739136dc9f51a7dc9db93ce0384a1

**Comment by binji** [comment]
This looks like a good start, though you'll also need to allocate space for the stack and assign the stack pointer value.

**Comment by jfbastien** [comment]
I was thinking about hacking something in the runtime for now, I'll give that a try over the weekend.

**Comment by kripken** [comment]
There's a runtime? Where?

**Comment by jfbastien** [comment]
The JavaScript runtime that starts the main wasm program. I'll have to also figure out how binaryen-shell does this! It's hard coded for now, I'm wondering if we can make it more general.

**Comment by kripken** [comment]
Where is this JavaScript runtime?

**Comment by jfbastien** [comment]
I hacked a thing for the waterfall's GCC torture tests:
https://github.com/WebAssembly/waterfall/blob/master/src/test/wasm.js

Pretty similar to what you already have, and in dire need of a real libc (which I intend to do next week). The code itself is throwaway, the main idea is solid though (well, except for the JS libc).

**Comment by kripken** [comment]
Thanks for the link.

Not sure what you are saying it's similar to?

And what is the main idea that you refer to, that is solid?

As we've already said, let's talk on monday about the libc stuff. I really hope we can work together and have a single toolchain.

**Comment by jfbastien** [comment]
I mean this one is similar: https://github.com/WebAssembly/binaryen/blob/master/bin/wasm.js

The libc I'm making in JS just serves the FFI needs, which I want to do through musl next week. In the meantime it'll tie us over, and the libc is easier to integrate so I think it's useful even when we have musl (and fun to write!).

What's solid is the way we start wasm and communicate with it. Drop the FFI part from my wasm.js and I still like it :-)

I was thinking about moving libc.js to another repo, and just keeping the wasm setup here (effectively the loader). Or something along those lines, my implementation will probably also have libm and compiler-rt (a.k.a. libgcc_s), maybe libpthread when we add that. All of those can be done in JS, but would be better in wasm with musl. Let's discuss on Monday :-)

**Comment by kripken** [comment]
Well, the main thing in wasm.js is the compiled wasm interpreter, which is why I was confused by your comparison. In happens to contain compiled musl, but for support of that interpreter - not for the goal you are talking about here, which is to support the actual compiled code. Emscripten would place a build of musl together with that code, in it's own file.

Anyhow, I'm confused about your libc.js. Why do you need it, even temporarily? There are existing working ports of musl, by the emscripten community, and they are tested already in the binaryen test suite. Why do you need a temporary solution for libc?

I guess that's what we'll discuss more on Monday.

**Comment by binji** [comment]
You're asking the purpose of writing code when a working, tested implementation already exists? :wink:

**Comment by kripken** [comment]
I must be the target of some kind of joke here :) Yes, that is exactly what I'm asking - isn't it a reasonable question?

**Comment by binji** [comment]
Yes, it is reasonable. I was making a little joke about `sexpr-wasm` and `wasm-as`. Anyway, there are plenty of reasons why it may be useful, expedient or convenient to write new code instead of reusing existing code.

In this case, I'd say that it is likely that it is kind of fun to implement some of the simpler libc functions, and it sounds like JF was going to throw away the JS implementation anyway. But I'm just guessing.

**Comment by jfbastien** [comment]
Correct, I wanted to get the basics up to pass the GCC torture tests. Then I cleaned it up and added a few easy things. Fun times.

**Comment by kripken** [comment]
Agreed, there can be good reasons to write new code despite existing code. I was just curious what the reasons were here.

**Comment by jfbastien** [comment]
Main reason: quick and easy to get GCC torture tests passing without much fuss. Reason to keep working on it: it's the weekend and I had fun. :-)

**Comment by kripken** [comment]
Ok, thanks.
