### ISSUE TITLE
Change --sync-lkgr to use the public lkgr URL

### ISSUE THREAD

**Issue by jgravelle-google** [WebAssembly/waterfall#194]
`--sync-lkgr` uses `cloud.Download` (https://github.com/WebAssembly/waterfall/blob/master/src/build.py#L723), which uses `gsutil.py`, which is an unnecessary dependency when we could just use public URLs (e.g. https://storage.googleapis.com/wasm-llvm/builds/linux/lkgr.json)

**Comment by sbc100** [comment]
I think its find, for consistency.  Using `wget` or `curl` would have their own issues (in windows especially).   Unless we want to switch to a pure python impl?
