### ISSUE TITLE
Links to prebuilt binaries missing

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/waterfall#197]
Say I want to download prebuilt binaries. [This page](https://wasm-stat.us/console)'s download button for "Archive binaries" takes me here:
https://storage.googleapis.com/wasm-llvm/builds/mac/4907/wasm-torture-c-4907.tbz2

The individual buildbot log does the same.

If I expand the log's output:
https://wasm-stat.us/builders/mac/builds/4907/steps/Archive%20binaries/logs/stdio

The reason becomes apparent: multiple uploads were bundled into one step.

This line is what the "download" button should point at:

```
subprocess.check_call(`/usr/bin/python /b/depot_tools/gsutil.py cp -a public-read /b/build/slave/mac/build/src/src/work/wasm-install.tbz2 gs://wasm-llvm/builds/mac/4907/wasm-binaries-4907.tbz2`, cwd=`/b/build/slave/mac/build/src/src`)
Copying file:///b/build/slave/mac/build/src/src/work/wasm-install.tbz2 [Content-Type=application/x-tar]...
```

But instead it also has this:

```
@@@STEP_LINK@download@https://storage.googleapis.com/wasm-llvm/builds/mac/4907/wasm-torture-c-4907.tbz2@@@
```

While we're here... Why rename "wasm-install.tbz2" to "wasm-binaries-4907.tbz2"? Install to binaries is weird (because a local build doesn't produce the same folders as what's archived)... but having the build number twice in the path is even weirder. I used to be able to do this:

```
https://storage.googleapis.com/wasm-llvm/builds/$PLATFORM/$PLATFORM_LKGR/wasm-install.tbz2
```

That's a useful property which I think should be kept.

**Comment by binji** [comment]
Probably would be nice to have `wasm-install.tbz2` be a symlink to the tarball in that directory. I personally like having the build number in the filename so I can easily see what version I have locally.

**Comment by jfbastien** [comment]
It's weird to have the folder *and* the filename then. It should be only in one place IMO.

**Comment by sbc100** [comment]
I think I broke this in 470303ab41c487bba767bf224cd6d5132073b4e5.  Although I think the "Compile LLVM Torture" previously suffered from the same issue.

Perhaps its worth asserting that each step has exactly one download link..  Or we would add the name of the file to the doadload URL so they won't colide.

**Comment by binji** [comment]
Just ran into this bug (incorrect link to prebuilt binaries). Anyone looking at fixing this?

**Comment by sbc100** [comment]
I will take a look yes
