### ISSUE TITLE
emcc_wrapper.sh doens't work on MacOS

### ISSUE THREAD

**Issue by jfbastien** [WebAssembly/waterfall#198]
`readlink -f` isn't a thing that Just Works. The installed `em++` yields:

```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

**Comment by dschuff** [comment]
Closing this as obsolete, and because we are moving the code (see #698). If there is an issue with the build scripts, please file an issue against [EMSDK](https://github.com/emscripten-core/emsdk/)
