### ISSUE TITLE
LKGR link on main waterfall page to downloadable binaries

### ISSUE THREAD

**Issue by binji** [WebAssembly/waterfall#206]
It would be convenient to be able to download the most recently built binary bundle from the main page. Recently the waterfall was very red, and it wasn't clear when the last good build was.

**Comment by dschuff** [comment]
Closing this as obsolete, and because we are moving the code (see #698). If there is an issue with the build scripts, please file an issue against [EMSDK](https://github.com/emscripten-core/emsdk/)
