### ISSUE TITLE
Create wasm-clang symlinks

### ISSUE THREAD

**Issue by dschuff** [WebAssembly/waterfall#321]
Now that wasm32-unknown-unknown-wasm is the default triple (instead of wasm32-unknown-unknown-elf), we should be able to name the compiler wasm32-unknown-unknown-clang (or probably just wasm-clang) and that should cause wasm (rather than x86) to be the default triple. Then clang would just work without any flags.

**Comment by sbc100** [comment]
Hmm.. didn't see the default change.. but that certainly looks like the reason the waterfall is now broken.   I wonder how that change slipped through my filter.

**Comment by sbc100** [comment]
Perhaps we could also make --target=wasm work (i.e be the same as --target=wasm32)

**Comment by dschuff** [comment]
er... sorry, wasm32-clang should just work. Don't know about un-suffixed wasm, that might involve setting up another triple. Or maybe there's some way to make an alias or something.

**Comment by sbc100** [comment]
I for one would prefer to call that target just "wasm" .. and introduce "wasm64" much later when it arrives.  This is the case for "arm" and "arm64" for example so there is precedent.

**Comment by sbc100** [comment]
How do we go about making these links.. presumably the llvm build system has a way to creating these for us?

**Comment by dschuff** [comment]
Maybe? For nacl we ended up just doing it in the build scripts that packaged the toolchain.
Also wrt wasm vs wasm32 it looks like it's easy to just have 2 things that alias (e.g. arm64 and aarch64). And I think it makes sense to do that, but we should probably discuss it a bit more broadly.

**Comment by sbc100** [comment]
This now done
