### ISSUE TITLE
Disable emcc sanity checks for child processes to remove sleep hack

### ISSUE THREAD

**Issue by aheejin** [WebAssembly/waterfall#331]
TODO: Disable emcc sanity checks for child processes in emscripten and remove this hack. Looks like some related work is underway kripken/emscripten#6124.

https://github.com/WebAssembly/waterfall/blob/53ed3e7b474d5044527b09239fcf02df9fe01ea4/src/build.py#L1135-L1153

**Comment by dschuff** [comment]
Closing this as obsolete, and because we are moving the code (see #698). If there is an issue with the build scripts, please file an issue against [EMSDK](https://github.com/emscripten-core/emsdk/)
