### ISSUE TITLE
mac os with compile error

### ISSUE THREAD

**Issue by wengjunxiao** [WebAssembly/waterfall#347]
when I complie the code use the commend with mac os bellow:

> git clone https://github.com/eosio/eos --recursive
> cd eos
> ./eosio_build.sh
> 
 I get the error bellow, do somebody know how to solve it ?

> 
> -- Configuring Eos on OS X
> -- binaryen building with -std=c++11
> -- binaryen building for platform x86-64
> -- binaryen building with -Wall
> -- binaryen building with -Werror
> -- binaryen building with -Wextra
> -- binaryen building with -Wno-unused-parameter
> -- binaryen building with -fno-omit-frame-pointer
> -- binaryen building with -fPIC
> -- binaryen building with -O2
> -- binaryen building with -UNDEBUG
> -- Could NOT find WASM (missing: WASM_CLANG)
> CMake Error at CMakeModules/wasm.cmake:8 (message):
>   No WASM compiler cound be found (make sure WASM_ROOT is set)
> Call Stack (most recent call first):
>   CMakeLists.txt:194 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/weng/eos/build/CMakeFiles/CMakeOutput.log".

**Comment by dschuff** [comment]
This is probably a question for the EOS repo (where wasm.cmake is define) since it appears they are using all the constituent toolchain parts independently, but from a brief glance at their wasm.cmake. But I'm guessing you need to set a WASM_ROOT environment variable that points to clang?

**Comment by dschuff** [comment]
Closing this as obsolete, and because we are moving the code (see #698). If there is an issue with the build scripts, please file an issue against [EMSDK](https://github.com/emscripten-core/emsdk/)
