### ISSUE TITLE
libstdc++ on waterfall bots is too old to biuld llvm HEAD

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/waterfall#467]
At least it will be soon:

CMake Error at cmake/modules/CheckCompilerVersion.cmake:102 (message):
  libstdc++ version should be at least 5.1 because LLVM will soon use new C++
  features which your toolchain version doesn't support.  You can temporarily
  opt out using LLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN, but very soon your
  toolchain won't be supported.

**Comment by sbc100** [comment]
It looks like the most recent version in trusty is: https://packages.ubuntu.com/trusty/libstdc++6-4.7-dev

Which I guess is 4.7 so not recent enough?

**Comment by sbc100** [comment]
Looks like we are currently running trusty (The bots say they are `chrome-trusty-18042300-b7223b463e3`).

I would be good to update the linux builds to a more recent LTS.  Either of the following should be fine:

- Ubuntu 16.04.6 LTSXenial Xerus
- Debian 9 Stretch

**Comment by sbc100** [comment]
Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=939830

**Comment by binji** [comment]
Is it necessary to update the OS? Maybe it's simpler to install a newer compiler via PPA?

**Comment by sbc100** [comment]
My understanding is that we can't just login and make change to the base image ourselves? I was assuming that these swarming bots are often re-imaged, or at least we cannot assume they won't be re-imaged/replaced.

Or do you mean we should have the build script run "sudo apt-get install ..." ?    I'm not sure we run as root so we probably can't do this..

**Comment by binji** [comment]
Oh right, I see what you mean.

**Comment by dschuff** [comment]
Another option is just to build our own libc++ and link against that. For pnacl-clang we build the DSO; Chrome just links against libc++ statically; either way should work. More generally we should maybe consider building with Chrome's sysroot rather than whatever is on the bots; that seems likely to get even better compatibility and reproducibility. We also do that with pnacl-clang; switching was quite painless.

**Comment by sbc100** [comment]
I agree... but I still think that we should update the base image.  Running trusty on the bots on 2019 doesn't make any sense.

**Comment by sbc100** [comment]
Fixed via this chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=939830#c15
