### ISSUE TITLE
Can we delete test_wasm_simd.py?

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/waterfall#479]

**Comment by tlively** [comment]
Yes, I believe so. It tests SIMD via simd.js and asm2wasm, which is a path for using SIMD that is no longer recommended or supported. I don't think there is any need to test this if we don't plan to continue supporting it and if we don't particularly care if it breaks.

**Comment by sbc100** [comment]
Would you mind sending a PR to delete it?
