### ISSUE TITLE
Include sanitizer library in build

### ISSUE THREAD

**Issue by kripken** [WebAssembly/waterfall#51]
It would be useful for https://github.com/WebAssembly/binaryen/pull/557 to have the clang from the waterfall be sanitzer-enabled, then we could use it to build on travis. Looks like what's blocking this is that

 * `libclang_rt.ubsan_standalone-x86_64.a`
 * `libclang_rt.asan-x86_64.a`
 * `libclang_rt.tsan-x86_64.a`

are missing, e.g.

````
/usr/bin/ld: cannot find

  /home/travis/build/WebAssembly/binaryen/test/wasm-install/wasm-install/bin/../lib/clang/3.9.0/lib/linux/libclang_rt.ubsan_standalone-x86_64.a:
````

**Comment by dschuff** [comment]
Fixed by #52
