### ISSUE TITLE
binaryen-shell is hardcoded, how to update?

### ISSUE THREAD

**Issue by kripken** [WebAssembly/waterfall#55]
Looks like `binaryen-shell` is hardcoded in `build.py` and `execute_files.py`. We'd like to rename it (see https://github.com/WebAssembly/binaryen/pull/592#issuecomment-231234335). What would be the best way to do it?

One option is to change it and tolerate breakage temporarily (on at least one of the two locations of binaryen and the waterfall).

Another is to refactor the code so it receives the tool name somehow.

**Comment by jfbastien** [comment]
You can duplicate at least in `execute_files.py`, and support both for a while?

**Comment by dschuff** [comment]
I'm not sure it's worth even doing that. It's not like we expect name changes to be common, or that updating the scripts to accommodate name changes is hard. Maybe just prepare a PR in the waterfall to handle the change, and land it when binaryen changes.

**Comment by kripken** [comment]
@jfbastien: i guess supporting both could be done by trying both and ignoring the one that fails, but seems messy...

@dschuff: sounds good, i can prepare a pr for that. if we find something better we can ignore it.

**Comment by kripken** [comment]
Merged on both repos.
