### ISSUE TITLE
Proposal: Add debian package, and archive alongside tgz file

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/waterfall#82]

**Comment by sbc100** [comment]
The initial packages are were committed in #83.

They are being uploaded by the linux builder for every builld. e.g.:
https://storage.googleapis.com/wasm-llvm/builds/linux/11637/wasm-toolchain_0.1_amd64.deb

**Comment by bp-dev** [comment]
Are more recent versions still being built as debs?
I've been trying to locate them but failed to find any clue on https://wasm-stat.us/console

**Comment by sbc100** [comment]
Yup, just find a successful build (e.g. https://wasm-stat.us/builders/linux/builds/34316) and search for Debian.  There should be download link right there.

**Comment by bp-dev** [comment]
Thanks!
I'll add that build artefacts are browsable at http://gsdview.appspot.com/wasm-llvm/builds/linux/?marker=builds%2Flinux%2F33656%40 to locate the latest version (thanks reddit for that hint)
